### ISSUE TITLE
Not Working on XZ1 CarbonROM 8 (Android Q)

### ISSUE THREAD

**Issue by TuxNews** [kitsunyan/foxy-boot#10] opened 2020-06-11 13:02 UTC
![photo_2020-06-11_15-02-08](https://user-images.githubusercontent.com/45686773/84388252-8a5de280-abf4-11ea-818a-4e34eed7967e.jpg)

Not working.

**Comment by kitsunyan** [comment] 2020-06-15 09:03
Duplicate of https://github.com/kitsunyan/foxy-boot/issues/8.

**Closed as completed by kitsunyan** 2020-06-15 09:03 UTC
